# Generated by Django 6.0.6 on 2026-07-03 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('second_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, help_text='Nombre completo auto-generado o ingresado', max_length=400)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('U', 'Desconocido')], default='U', max_length=1)),
                ('nationality', models.CharField(blank=True, default='Venezolana', max_length=100, null=True)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('MISSING', 'Desaparecido'), ('FOUND_ALIVE', 'Encontrado con Vida'), ('FOUND_DECEASED', 'Encontrado Fallecido'), ('UNKNOWN', 'Desconocido')], default='MISSING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('case', models.OneToOneField(help_text='Caso asociado a esta persona desaparecida', on_delete=django.db.models.deletion.CASCADE, related_name='missing_person', to='core.case')),
            ],
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Descripción de la ubicación o dirección', max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('source', models.CharField(help_text='Fuente de donde proviene el reporte de ubicación', max_length=200)),
                ('reported_at', models.DateTimeField(help_text='Fecha y hora en que se reportó el avistamiento')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='subjects.missingperson')),
            ],
            options={
                'verbose_name_plural': 'Location histories',
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='subjects.missingperson')),
            ],
            options={
                'verbose_name_plural': 'Aliases',
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(help_text='Parentesco (ej. Madre, Padre, Hermano)', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='subjects.missingperson')),
            ],
        ),
    ]
