# Generated by Django 6.0.6 on 2026-07-03 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('HOSPITAL', 'Hospital / Centro de Salud'), ('SHELTER', 'Refugio / Albergue'), ('RED_SOCIAL', 'Redes Sociales (X, Facebook, etc.)'), ('SHEET', 'Google Sheets Colaborativos'), ('API', 'API Externa / Base de Datos Pública'), ('OTHER', 'Otra fuente')], default='OTHER', max_length=30)),
                ('url', models.URLField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Investigador u operador encargado de ejecutar la investigación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(help_text='Caso asociado a la investigación', on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='core.case')),
            ],
        ),
        migrations.CreateModel(
            name='SourceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(help_text='Texto o información recuperada de la fuente')),
                ('url', models.URLField(blank=True, help_text='Enlace directo a la información encontrada', null=True)),
                ('confidence', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], default='MEDIUM', help_text='Nivel de confianza en que el resultado coincida con la búsqueda', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scraper.investigation')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='scraper.source')),
            ],
        ),
    ]
