# Generated by Django 6.0.6 on 2026-07-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('WEB', 'Web Chat')], default='WHATSAPP', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('PENDING_REVIEW', 'Pendiente por Revisión'), ('ARCHIVED', 'Archivada')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('USER', 'Usuario / Familiar'), ('OPERATOR', 'Operador'), ('SYSTEM', 'Sistema / Bot')], max_length=20)),
                ('message', models.TextField()),
                ('twilio_sid', models.CharField(blank=True, help_text='Identificador único del mensaje en Twilio', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
