# Generated by Django 6.0.6 on 2026-07-03 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Caso asociado a esta conversación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='core.case'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.conversation'),
        ),
    ]
