# Generated by Django 6.0.6 on 2026-07-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='bot_state',
            field=models.CharField(default='IDLE', help_text='Estado actual en el flujo del menú', max_length=50),
        ),
        migrations.AddField(
            model_name='conversation',
            name='session_data',
            field=models.JSONField(blank=True, default=dict, help_text='Respuestas parciales del reportante'),
        ),
    ]
