# Generated by Django 6.0.6 on 2026-07-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_conversation_bot_state_conversation_session_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='channel',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp')], default='WHATSAPP', max_length=20),
        ),
    ]
